-- FireflySMP Website V15
-- Run this in Supabase Dashboard -> SQL Editor -> New query.
-- Safe to run multiple times.

create table if not exists public.staff_users (
  username_key text primary key,
  username text not null,
  display_name text not null,
  role text not null default 'Helper'
    check (role in ('Owner', 'Admin', 'Developer', 'Moderator', 'Helper')),
  pin_salt text not null,
  pin_hash text not null,
  enabled boolean not null default true,
  visible boolean not null default true,
  display_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staff_permissions (
  username_key text not null
    references public.staff_users(username_key) on delete cascade,
  permission text not null
    check (permission in ('edit_wiki', 'edit_staff', 'access_control', 'manage_access')),
  primary key (username_key, permission)
);

create table if not exists public.wiki_categories (
  name text primary key,
  display_order integer not null default 100,
  created_at timestamptz not null default now()
);

create table if not exists public.wiki_pages (
  id text primary key,
  category_name text not null
    references public.wiki_categories(name)
    on update cascade,
  title text not null,
  description text not null default '',
  content text not null default '',
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wiki_drafts (
  id text primary key,
  category_name text not null,
  title text not null,
  description text not null default '',
  content text not null default '',
  edited_by text,
  saved_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_username text not null,
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_staff_users_public
  on public.staff_users (visible, enabled, display_order);

create index if not exists idx_staff_users_role
  on public.staff_users (role);

create index if not exists idx_wiki_pages_category
  on public.wiki_pages (category_name);

create index if not exists idx_audit_logs_created
  on public.audit_logs (created_at desc);

-- The browser never queries Supabase directly. These tables are backend-only.
-- Enabling RLS with no browser policies blocks anon/authenticated Data API access.
alter table public.staff_users enable row level security;
alter table public.staff_permissions enable row level security;
alter table public.wiki_categories enable row level security;
alter table public.wiki_pages enable row level security;
alter table public.wiki_drafts enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.staff_users from anon, authenticated;
revoke all on table public.staff_permissions from anon, authenticated;
revoke all on table public.wiki_categories from anon, authenticated;
revoke all on table public.wiki_pages from anon, authenticated;
revoke all on table public.wiki_drafts from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;

-- Default Wiki category for fresh installs.
insert into public.wiki_categories(name, display_order)
values ('General', 0)
on conflict (name) do nothing;
